In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('大立光2023-2025股價表 - 工作表1.csv')
df.head(5)

,代號,名稱,年月日,收盤價(元),成交量(千股),成交值(千元),報酬率％,三日報酬率,週轉率％,流通在外股數(千股),...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
0,3008,大立光,2025/02/27,"2,700",904,"2,454,462",-2.3508,-1.64%,0.6773,"133,468",...,3.6111,-65.0,2.3508,"2,700","2,970","2,430",NaN,NaN,NaN,TSE
1,3008,大立光,2025/02/26,"2,765",467,"1,282,758",1.0969,1.10%,0.3499,"133,468",...,3.5262,30.0,1.6453,"2,765","3,040","2,490",NaN,NaN,NaN,TSE
2,3008,大立光,2025/02/25,"2,735",741,"2,040,562",-0.3643,-0.91%,0.5552,"133,468",...,3.5649,-10.0,2.1858,"2,735","3,005","2,465",NaN,NaN,NaN,TSE
3,3008,大立光,2025/02/24,"2,745",276,"757,978",0.3656,1.29%,0.2068,"133,468",...,3.5519,10.0,1.0969,"2,745","3,015","2,475",NaN,NaN,NaN,TSE
4,3008,大立光,2025/02/21,"2,735",545,"1,492,353",-0.9058,0.74%,0.4083,"133,468",...,2.6965,-25.0,1.8116,"2,735","3,005","2,465",NaN,NaN,NaN,TSE

In [3]:
df_date_roi = df[['年月日' ,'三日報酬率']]
df_date_roi

            年月日   三日報酬率
0    2025/02/27  -1.64%
1    2025/02/26   1.10%
2    2025/02/25  -0.91%
3    2025/02/24   1.29%
4    2025/02/21   0.74%
..          ...     ...
510  2023/01/09   5.95%
511  2023/01/06   5.06%
512  2023/01/05     NaN
513  2023/01/04     NaN
514  2023/01/03     NaN

[515 rows x 2 columns]

In [4]:
df_date_roi['三日報酬率'] = df_date_roi['三日報酬率'].str.replace('%', '').astype(float)
df_date_roi['年月日'] = pd.to_datetime(df_date_roi['年月日'])
df_date_roi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年月日     515 non-null    datetime64[ns]
 1   三日報酬率   512 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 8.2 KB

C:\Users\emily\AppData\Local\Temp\ipykernel_15304\3555151588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_date_roi['三日報酬率'] = df_date_roi['三日報酬率'].str.replace('%', '').astype(float)
C:\Users\emily\AppData\Local\Temp\ipykernel_15304\3555151588.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_date_roi['年月日'] = pd.to_datetime(df_date_roi['年月日'])

In [5]:
#迭代
df_date_roi.shape[0]
df_date_roi['當天文章類別'] = ''
for i in range(df_date_roi.shape[0] - 3):
    roi = df_date_roi['三日報酬率'][i]
    if roi >= 5:
        df_date_roi.at[i+3, '當天文章類別'] = '漲'
    elif roi <= -5:
        df_date_roi.at[i+3, '當天文章類別'] = '跌'
    else:
        df_date_roi.at[i+3, '當天文章類別'] = '平'
df_date_roi = df_date_roi.iloc[3:514] #因為前面三個沒有後面的日子幫忙判斷
df_date_roi

C:\Users\emily\AppData\Local\Temp\ipykernel_15304\325467581.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_date_roi['當天文章類別'] = ''

           年月日  三日報酬率 當天文章類別
3   2025-02-24   1.29      平
4   2025-02-21   0.74      平
5   2025-02-20   0.91      平
6   2025-02-19   1.50      平
7   2025-02-18   0.37      平
..         ...    ...    ...
509 2023-01-10   3.81      跌
510 2023-01-09   5.95      平
511 2023-01-06   5.06      平
512 2023-01-05    NaN      平
513 2023-01-04    NaN      漲

[511 rows x 3 columns]

In [6]:
df_date_roi['當天文章類別'].value_counts()

當天文章類別
平    443
漲     41
跌     27
Name: count, dtype: int64

把兩個資料集合併

In [7]:
df_news = pd.read_csv('df_largon_with_date_news.csv')
df_news.head(5)

,post_time,title,content
0,2023-01-03 13:50:25,台積電重返450元！台股強攻翻紅 指數漲86點收14224點,記者戴玉翔／台北報導台股今（3）日迎來 2023 年交易首日，開盤出師不利，盤中一度跌至 1...
1,2023-01-04 13:22:39,大立光及玉晶光雙雄領漲 光電類股大漲1％,光學雙雄-大立光（3008）及玉晶光（3406），今（4）日不畏蘋果被砍單、市值跌破2兆美元...
2,2023-01-04 14:09:22,台股終場小跌24點 光電族群續發威,[NOWnews今日新聞]美股2023年首個交易日4大指數皆走跌，台北股市今（4）日終場小跌...
3,2023-01-04 14:19:13,台股狹幅震盪小跌24點 人氣仍低迷,（中央社記者韓婷婷台北4日電）台股今天早盤雖一度受到美股收黑影響以低盤開出，但隨即在電子權值...
4,2023-01-04 15:05:13,台股多空交戰失守14200點 三大法人土洋對作賣超42.5億元,台股今 (4) 日在平盤上下遊走，光電族群表現強勢，其中，再生能源族群成為盤面多頭指標，不過...

In [8]:
df_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17576 entries, 0 to 17575
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_time  17576 non-null  object
 1   title      17576 non-null  object
 2   content    17576 non-null  object
dtypes: object(3)
memory usage: 412.1+ KB

In [9]:
df_news['post_time'] = pd.to_datetime(df_news['post_time']).dt.date
df_news.head(5)

,post_time,title,content
0,2023-01-03,台積電重返450元！台股強攻翻紅 指數漲86點收14224點,記者戴玉翔／台北報導台股今（3）日迎來 2023 年交易首日，開盤出師不利，盤中一度跌至 1...
1,2023-01-04,大立光及玉晶光雙雄領漲 光電類股大漲1％,光學雙雄-大立光（3008）及玉晶光（3406），今（4）日不畏蘋果被砍單、市值跌破2兆美元...
2,2023-01-04,台股終場小跌24點 光電族群續發威,[NOWnews今日新聞]美股2023年首個交易日4大指數皆走跌，台北股市今（4）日終場小跌...
3,2023-01-04,台股狹幅震盪小跌24點 人氣仍低迷,（中央社記者韓婷婷台北4日電）台股今天早盤雖一度受到美股收黑影響以低盤開出，但隨即在電子權值...
4,2023-01-04,台股多空交戰失守14200點 三大法人土洋對作賣超42.5億元,台股今 (4) 日在平盤上下遊走，光電族群表現強勢，其中，再生能源族群成為盤面多頭指標，不過...

In [10]:
df_ppt = pd.read_csv('df_largon_with_date_ppt.csv')
df_ppt.head(5)

,post_time,title,content
0,2023-01-04 11:55:06,Re: [新聞] 輝達攜手鴻海 打造自駕汽車平台,之前有推文有聊到其他車廠自動駕駛狀態 像是Benz 目前許多車廠都是買Nvidia套裝或者軟...
1,2023-01-04 18:55:29,[新聞] 謝金河：機會總在絕望中誕生,原文標題：謝金河：機會總在絕望中誕生 原文連結：https://reurl.cc/GXRD...
2,2023-01-05 11:59:23,[新聞] 日經：戴爾計劃2024年全面停用大陸製造,原文標題： 日經：戴爾計劃2024年全面停用大陸製造晶片 原文連結： https://ud...
3,2023-01-06 02:02:15,[新聞] 獨家》美企指控侵權 華碩、宏碁遭美調查,原文標題： 獨家》美企指控侵權 華碩、宏碁遭美調查 原文連結： https://ec...
4,2023-01-06 08:13:48,[新聞] HTC推新品！VIVE XR Elite登場 售價3490,原文標題： HTC推新品！VIVE XR Elite登場 售價34900元 原文連結： h...

In [11]:
df_ppt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_time  650 non-null    object
 1   title      650 non-null    object
 2   content    650 non-null    object
dtypes: object(3)
memory usage: 15.4+ KB

In [12]:
df_ppt['title'] = df_ppt['title'].str.replace('[新聞]', '', regex=False)
df_ppt['post_time'] = pd.to_datetime(df_ppt['post_time']).dt.date
df_ppt.head(5)

,post_time,title,content
0,2023-01-04,Re: 輝達攜手鴻海 打造自駕汽車平台,之前有推文有聊到其他車廠自動駕駛狀態 像是Benz 目前許多車廠都是買Nvidia套裝或者軟...
1,2023-01-04,謝金河：機會總在絕望中誕生,原文標題：謝金河：機會總在絕望中誕生 原文連結：https://reurl.cc/GXRD...
2,2023-01-05,日經：戴爾計劃2024年全面停用大陸製造,原文標題： 日經：戴爾計劃2024年全面停用大陸製造晶片 原文連結： https://ud...
3,2023-01-06,獨家》美企指控侵權 華碩、宏碁遭美調查,原文標題： 獨家》美企指控侵權 華碩、宏碁遭美調查 原文連結： https://ec...
4,2023-01-06,HTC推新品！VIVE XR Elite登場 售價3490,原文標題： HTC推新品！VIVE XR Elite登場 售價34900元 原文連結： h...

In [13]:
combined_df = pd.concat([df_ppt, df_news], ignore_index=True)
combined_df.shape

(18226, 3)

In [14]:
#開始對照
# 建立對照表：用年月日對應類別
class_mapping = df_date_roi.set_index('年月日')['當天文章類別']

# 使用 .map() 對齊日期，對照文章類別
combined_df['class'] = combined_df['post_time'].map(class_mapping)

combined_df.head(5)

,post_time,title,content,class
0,2023-01-04,Re: 輝達攜手鴻海 打造自駕汽車平台,之前有推文有聊到其他車廠自動駕駛狀態 像是Benz 目前許多車廠都是買Nvidia套裝或者軟...,漲
1,2023-01-04,謝金河：機會總在絕望中誕生,原文標題：謝金河：機會總在絕望中誕生 原文連結：https://reurl.cc/GXRD...,漲
2,2023-01-05,日經：戴爾計劃2024年全面停用大陸製造,原文標題： 日經：戴爾計劃2024年全面停用大陸製造晶片 原文連結： https://ud...,平
3,2023-01-06,獨家》美企指控侵權 華碩、宏碁遭美調查,原文標題： 獨家》美企指控侵權 華碩、宏碁遭美調查 原文連結： https://ec...,平
4,2023-01-06,HTC推新品！VIVE XR Elite登場 售價3490,原文標題： HTC推新品！VIVE XR Elite登場 售價34900元 原文連結： h...,平

In [15]:
combined_df['class'].value_counts()

class
平    13818
漲     1326
跌     1028
Name: count, dtype: int64

文章分類(漲)

In [19]:
#先分漲
df_3d5_up = combined_df[combined_df['class']=='漲']
df_3d5_up.shape

(1326, 4)

In [20]:
#漲的只留title跟content 
df_3d5_up = df_3d5_up[['title','content']]
df_3d5_up

,title,content
0,Re: 輝達攜手鴻海 打造自駕汽車平台,之前有推文有聊到其他車廠自動駕駛狀態 像是Benz 目前許多車廠都是買Nvidia套裝或者軟...
1,謝金河：機會總在絕望中誕生,原文標題：謝金河：機會總在絕望中誕生 原文連結：https://reurl.cc/GXRD...
31,順德、界霖 法人喊買,原文標題：順德、界霖 法人喊買 原文連結：https://udn.com/news/st...
32,雷虎攜手邑錡開發美軍軍規無人機,原文標題：雷虎攜手邑錡開發美軍軍規無人機，搶攻MIT無人機市場 原文連結：https:/...
95,《半導體》車用IGBT量產出貨 聯電USJC與,原文標題：《半導體》車用IGBT量產出貨 聯電USJC與DENSO合攻商機 原文連結： ...
...,...,...
16280,【公告】雷笛克光學研發主管異動,日 期：2024年11月21日公司名稱：雷笛克光學 (5230)主 旨：雷笛克光學研發主管異...
16281,vivo今發布新旗艦機X200 遠傳開放預購最高折5000元,vivo與聯發科技及蔡司合作推出全新的vivo X200旗艦系列，於今（21）日發表會正式亮...
16282,vivo X200系列正式登台 搶旗艦手機商機,vivo今（21）日舉辦新機發表會，旗下X200系列正式登台，除搭載全球首發的聯發科技天璣9...
16283,立隆：沒有缺席AI伺服器 明年營運看正成長,（中央社記者鍾榮峰台北2024年11月21日電）被動元件鋁質電容廠立隆電 (2472) 董事...
16284,國巨吃證交所罰單！ 子公司遭駭客攻擊太晚發重訊,被動元件大廠國巨（2327）子公司基美（KEMET)在2年多前，美國子公司爆發資安事件卻延遲...

In [21]:
#儲存成csv檔
df_3d5_up.to_csv('3天5%的資料集/df_3d5_up.csv', index=False, encoding='utf-8-sig')

文章分類(跌)

In [22]:
#分跌
df_3d5_down = combined_df[combined_df['class']=='跌']
df_3d5_down.shape

(1028, 4)

In [23]:
#只留title跟content 
df_3d5_down = df_3d5_down[['title','content']]
df_3d5_down

,title,content
142,手機升級大戰開打！大立光不僅重返股王,原文標題： 手機升級大戰開打！大立光不僅重返股王 林恩平：8月訂單比7月好 原文連結： ...
198,9月ETF配息一次看！這檔「近4次配息金額,原文標題： 9月ETF配息一次看！這檔「近4次配息金額」達3.65元 殖利率最高是它 原文...
199,全球首條無人半導體封裝生產線亮相！三星,原文標題： 全球首條無人半導體封裝生產線亮相！三星宣佈成功實現自動化 原文連結： ht...
200,鉅亨速報 - Factset 最新調查：大立光(30,原文標題： 鉅亨速報 - Factset 最新調查：大立光(3008-TW)EPS預估上修...
201,華通：8月營收創今年新高 下半年看旺,原文標題：華通：8月營收創今年新高 下半年看旺 原文連結：https://mefun.tw...
...,...,...
15583,是否收購英特爾IDM業務 魏哲家：不考慮收購IDM廠,（中央社記者張建中新竹2024年10月17日電）英特爾（Intel）營運面臨困境，法人關注台...
15584,蘋果傳研發超薄、摺疊手機 大立光：討論開發中,（中央社記者江明晏台北2024年10月17日電）外傳蘋果正研發超薄手機與摺疊手機，針對技術難...
15585,【公告】揚明光代子公司昆山揚明光學有限公司累計取得理財產品達應行標準,日 期：2024年10月17日公司名稱：揚明光 (3504)主 旨：代子公司昆山揚明光學有限...
15586,微信上的中國／畢業了，才知道有滴滴代彈…,微信萬花筒 神州蒼生的日常、思考與生活<BR> 經濟不振，中國藝術專業的學生似乎有了新去處...
15587,大立光謹慎看Q4 外資嚴陣以待,光學族群股王大立光（3008）法說會落幕，單季每股稅後純益（EPS）寫近八季以來最佳、達49...

In [24]:
#儲存成csv檔
df_3d5_down.to_csv('3天5%的資料集/df_3d5_down.csv', index=False, encoding='utf-8-sig')